### PR TITLE
Added sync command

### PR DESCRIPTION
**Pull request by Denis-REMACLE**
/!\ I have no prior experience with discord bots /!\\

I forgot to add my reddit username in a request and i tried to use a command that looks like this

_[11:42] cr1ng3: @LPUBeltBot sync u/winstonsmth01_

But the command didn't exist and someone suggested to add the command.

So i tried to implement it.

It probably needs to check if user has already been flaired on reddit.

### CODE REVIEW

**Comment by theelous3** [comment]
This command should be moderator only. Example: https://github.com/theelous3/BeltBot/blob/master/bot/beltbot.py#L131

**Comment by Denis-REMACLE** [comment]
I have added the role requirement.
Now the command looks like this :
_@LPUBeltBot sync belt\-color reddit\-username_

**Comment by theelous3** [comment]
hey! so sorry, one last thing - the flair to give the user should be selected from the user in discord.

**Comment by theelous3** [comment]
I'm going to merge this in the mean time - but consider it kinda broken :)

**Pull request merged**
